In [1]:
from content_rs_app import content_recommender
from collaborative_rs_app import svd_collaborative_model

In [4]:
def hybrid_model(user_id, title, num_movie=30):
    movies_list = content_recommender(title, num_movie=num_movie)
    movies_id = list(movies_list.index)
    rank = []
    for movie_id in movies_id:
        score = svd_collaborative_model.predict(user_id, movie_id).est
        rank.append((score, movies_list[movie_id]))
    
    result = sorted(rank, key=lambda x: x[0], reverse=True)
    return result

In [7]:
user_id = 1923
movie_name = "Toy Story"	
hybrid_model(user_id, movie_name, num_movie=20)

[(4.159802025437833, 'Toy Story 2'),
 (3.5852618254259423, 'Toy Story 3'),
 (3.5852618254259423, 'Sexual Life'),
 (3.5852618254259423, 'They Came Together'),
 (3.5852618254259423, 'Supporting Characters'),
 (3.5852618254259423, 'Invitation to Happiness'),
 (3.5852618254259423, 'In a Day'),
 (3.5852618254259423, 'In jeder Sekunde'),
 (3.5852618254259423, 'Diaries Notes and Sketches'),
 (3.5852618254259423, 'Sobriety'),
 (3.5852618254259423, 'Newlyweds'),
 (3.5852618254259423, 'Mars'),
 (3.5852618254259423, 'Loaded'),
 (3.5852618254259423, 'His New Profession'),
 (3.5852618254259423, 'Illicit'),
 (3.5852618254259423, 'Superstar Goofy'),
 (3.5852618254259423, 'Organize İşler'),
 (3.557135485763836, 'Animal Room'),
 (3.134201025191685, 'Keiner liebt mich'),
 (2.8463697699648973, 'Noises Off...')]

In [10]:
user_id = 2
movie_name = "Toy Story"	
hybrid_model(user_id, movie_name, num_movie=20)

[(3.463859910144663, 'Animal Room'),
 (3.432892079701506, 'Toy Story 3'),
 (3.432892079701506, 'Sexual Life'),
 (3.432892079701506, 'They Came Together'),
 (3.432892079701506, 'Supporting Characters'),
 (3.432892079701506, 'Invitation to Happiness'),
 (3.432892079701506, 'In a Day'),
 (3.432892079701506, 'In jeder Sekunde'),
 (3.432892079701506, 'Diaries Notes and Sketches'),
 (3.432892079701506, 'Sobriety'),
 (3.432892079701506, 'Newlyweds'),
 (3.432892079701506, 'Mars'),
 (3.432892079701506, 'Loaded'),
 (3.432892079701506, 'His New Profession'),
 (3.432892079701506, 'Illicit'),
 (3.432892079701506, 'Superstar Goofy'),
 (3.432892079701506, 'Organize İşler'),
 (3.3832964502709117, 'Toy Story 2'),
 (2.894559396709209, 'Keiner liebt mich'),
 (2.8085227896378053, 'Noises Off...')]

### get the intersection of rated movies and metadata csv

In [27]:
import pandas as pd

In [29]:
metadata_df = pd.read_csv("data/cleaned_movies_metadata.csv")
metadata_df.head(2)

,movieId,original_title,genres,original_language,overview,production_companies,production_countries
0,862,Toy Story,Animation Comedy Family,en,"Led by Woody, Andy's toys live happily in his ...",Pixar Animation Studios,United States of America
1,8844,Jumanji,Adventure Fantasy Family,en,When siblings Judy and Peter discover an encha...,TriStar Pictures Teitler Film Interscope Commu...,United States of America

In [30]:
ratings = pd.read_csv("data/cleaned_ratings.csv")
ratings.head(2)

   userId  movieId  rating
0       1      110     1.0
1       1      147     4.5

In [33]:
joined_df = ratings.merge(metadata_df, on="movieId", how="inner")

In [34]:
joined_df.head()

,userId,movieId,rating,original_title,genres,original_language,overview,production_companies,production_countries
0,1,110,1.0,Trois couleurs : Rouge,Drama Mystery Romance,fr,Red This is the third film from the trilogy by...,Zespół Filmowy TOR Le Studio Canal+ France 3 C...,France Poland Switzerland
1,1,147,4.5,Les Quatre Cents Coups,Drama,fr,"For young Parisian boy Antoine Doinel, life is...",Les Films du Carrosse Sédif Productions The Cr...,France
2,1,858,5.0,Sleepless in Seattle,Comedy Drama Romance,en,A young boy who tries to set his dad up on a d...,TriStar Pictures,United States of America
3,1,1246,5.0,Rocky Balboa,Drama,en,When he loses a highly publicized virtual boxi...,Columbia Pictures Revolution Studios Rogue Mar...,United States of America
4,1,1968,4.0,Fools Rush In,Drama Comedy Romance,en,Alex Whitman (Matthew Perry) is a designer fro...,Columbia Pictures,United States of America

In [35]:
joined_df[joined_df["original_title"] == "Toy Story"]

,userId,movieId,rating,original_title,genres,original_language,overview,production_companies,production_countries
79990,1923,862,3.0,Toy Story,Animation Comedy Family,en,"Led by Woody, Andy's toys live happily in his ...",Pixar Animation Studios,United States of America
87203,2103,862,5.0,Toy Story,Animation Comedy Family,en,"Led by Woody, Andy's toys live happily in his ...",Pixar Animation Studios,United States of America
228732,5380,862,1.0,Toy Story,Animation Comedy Family,en,"Led by Woody, Andy's toys live happily in his ...",Pixar Animation Studios,United States of America
266184,6177,862,4.0,Toy Story,Animation Comedy Family,en,"Led by Woody, Andy's toys live happily in his ...",Pixar Animation Studios,United States of America
280578,6525,862,4.0,Toy Story,Animation Comedy Family,en,"Led by Woody, Andy's toys live happily in his ...",Pixar Animation Studios,United States of America
...,...,...,...,...,...,...,...,...,...
11334543,268336,862,4.0,Toy Story,Animation Comedy Family,en,"Led by Woody, Andy's toys live happily in his ...",Pixar Animation Studios,United States of America
11338818,268391,862,3.0,Toy Story,Animation Comedy Family,en,"Led by Woody, Andy's toys live happily in his ...",Pixar Animation Studios,United States of America
11345744,268568,862,2.0,Toy Story,Animation Comedy Family,en,"Led by Woody, Andy's toys live happily in his ...",Pixar Animation Studios,United States of America
11418498,270422,862,4.0,Toy Story,Animation Comedy Family,en,"Led by Woody, Andy's toys live happily in his ...",Pixar Animation Studios,United States of America
11427738,270654,862,4.0,Toy Story,Animation Comedy Family,en,"Led by Woody, Andy's toys live happily in his ...",Pixar Animation Studios,United States of America